security:
    encoders:
        App\Entity\Appusers:
            algorithm: bcrypt
    providers:
        user:
            entity:
                class: App\Entity\Appusers
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern:    ^/
            http_basic: ~

            guard:
                authenticators:
                    - App\Security\AppAuthAuthenticator
            form_login:
                login_path: app_login
                check_path: login_check
                default_target_path: app_homepage
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   app_logout
                #target: /
    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        #- { path: ^/,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/,          roles: ROLE_USER }


